### ISSUE TITLE
Replace command needs to be renamed

### ISSUE THREAD

**Issue by AAA595** [dflat2/Pico#2]
ClassiCube 1.3.7 added a new builtin command `/client replace`
This conflicts with the `/client replace` in this plugin

**Comment by dflat2** [comment]
Fixed in latest commit. Unfortunately I cannot unload built-in commands. I've renamed `/Replace` to `/R`, and `/Place` to `/P`.

**Comment by AAA595** [comment]
May I suggest using `/PL` for place instead to be consistent with MCGalaxy?

**Comment by dflat2** [comment]
I've just changed to `/PL`. Every renamed command is listed in the `/Pico` command btw.
